appenders:
  logger_console:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} {h([{l}])} {M} > {m}{n}"
  logger_rolling_file:
    kind: rolling_file
    path: "./logs/errors.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} {M} > {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 10
        pattern: "./logs/errors{}.log"
root:
  level: debug
  appenders:
    - logger_console
loggers:
  log4rs_rust:
    level: error
    appenders:
      - logger_rolling_file
    additive: true
